// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pltdbsludpmsywzeufcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdGRic2x1ZHBtc3l3emV1ZmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjM2NzIsImV4cCI6MjA2OTI5OTY3Mn0.0IYDqgFTgR53mb6gc-iNxEsuYp3xI-DCQ1RZSZcpoxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});